DROP DATABASE IF EXISTS user_db;
CREATE DATABASE user_db;
USE user_db;

CREATE TABLE male(
  first_name VARCHAR(30) NOT NULL,
  email VARCHAR(90) NOT NULL,
  image BLOB NOT NULL,
  age TINYINT(2) NOT NULL,
  zip MEDIUMINT UNSIGNED NOT NULL, 
  gender ENUM("M","F") NOT NULL,
  password VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL,
  last_login TIMESTAMP NOT NULL,
  id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY);
  
CREATE TABLE female(
  first_name VARCHAR(30) NOT NULL,
  email VARCHAR(90) NOT NULL,
  image BLOB NOT NULL,
  age TINYINT(2) NOT NULL,
  zip MEDIUMINT UNSIGNED NOT NULL, 
  gender ENUM("M","F") NOT NULL,
  password VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL,
  last_login TIMESTAMP NOT NULL,
  id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY);

